handle rate limiting exceptions distinctly from other exceptions
fastly/sidekiq-prometheus pull request #28
Opened 2022-07-13 22:06 UTC by benedictfischer09

Sidekiq enterprise rate limiting raises a `Sidekiq::Limiter::OverLimit` exception when the rate limit is exceeded https://github.com/mperham/sidekiq/wiki/Ent-Rate-Limiting

It has middleware that catches that exception and re-queues the job rather then treating that exception as a true failure.  Depending on the ordering of middleware this gem might either count this as a failure or a success. Tracking this metric separately as neither a success nor failure seems ideal.

2022-07-14 17:51 UTC, benedictfischer09 commented
@leklund let me know if you have any thoughts on this, or if you need anything else from contributors to accept their work. Thanks!

2022-08-09 14:14 UTC, leklund commented
@benedictfischer09 I'm sorry I just saw this today when you closed the PR. I think this is a great addition as I've had to filter out OverLimit errors in the past.

2022-09-27 15:16 UTC, leklund requested changes
Made a couple of commit suggestions that *should* fix the CI failures because of rubocop. Once those are fixed and CI is passing I can merge and release.

2022-09-27 15:16 UTC, leklund commented on spec/sidekiq_prometheus/job_metrics_spec.rb
> +  end
more fixes for rubocop:

```suggestion
class Sidekiq::Limiter::OverLimit < StandardError; end
```

2022-09-29 15:11 UTC, leklund commented on spec/sidekiq_prometheus/job_metrics_spec.rb
> +class Sidekiq::Limiter::OverLimit < StandardError; end
```suggestion
  class Sidekiq::Limiter::OverLimit < StandardError; end
```

2022-09-29 18:56 UTC, leklund approved these changes

2022-10-04 13:31 UTC, merged